name: Release CI - Publish supports version site
on:
  push:
    branches:
      - 'support/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          server-id: github
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Generate site
        run: |
          echo "Generating test site for latest support release of branch ${GITHUB_REF#refs/heads/support/}"
          mvn -B clean verify site site:stage -Put,it,release
      - name: Publish site
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B scm-publish:publish-scm -Dscmpublish.subDirectory=${GITHUB_REF#refs/heads/support/}
